server:
  port: 8111

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8520 #实际转发的地址
          predicates:
            - Path=/api/**
      default-filters:
        - AddResponseHeader=source, start

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
